### ISSUE TITLE
USER STORY: Create an upcoming events section

### ISSUE THREAD

**Issue by WelshDan** [WelshDan/smittys-bar-booking#13]
EPIC: Upcoming events

As a **programmer** I can **create an upcoming events page** so that I can **inform the user of what future events are happening at the pub**

**Acceptance Criteria**
- [ ] Create an upcoming events page
- [ ] Show what upcoming events will be happening at the pub
- [ ] An option of sending an email to customers with "Upcoming events"

**Tasks**
- [ ] Design an upcoming events page
- [ ] Show what events are upcoming over a set period of time
- [ ] Make the page easily updatable
- [ ] Add a subscriptions check in box on the users profile to receive an email with the upcoming events
