### ISSUE TITLE
USER STORY: Create floor plan of pub

### ISSUE THREAD

**Issue by WelshDan** [WelshDan/smittys-bar-booking#2]
EPIC: Provide a detailed layout of the pub

As a **programmer** I can **provide layout details and information to the user** to **help them make a choice and entice them to book a table**

**Acceptance Criteria**
- [x] Create a basic overview floor plan of the pub in colour providing key information
- [x] Create a second overview plan of the pub including table numbers

**Tasks**
- [x] Create basic template for the floor plan for pub, including areas of the pub. This shows sections of the pub, important things like toilets and projector/tv positions. This can be in colour
- [x] Create second version of the floor plan with table numbers on each bookable table
