### ISSUE TITLE
USER STORY: Create admin login section

### ISSUE THREAD

**Issue by WelshDan** [WelshDan/smittys-bar-booking#4]
EPIC: Admin settings for owner

As an **admin** I can **edit and check information** to **help with bookings and meet user demands**

**Acceptance Criteria**
- [ ] Create full access to admin

**Tasks**
- [x] 1: Check admin has complete access to change all information
- [ ] 2: Check users have limited access, and can only change minimal information
