### ISSUE TITLE
USER STORY: Create a secure login to app

### ISSUE THREAD

**Issue by WelshDan** [WelshDan/smittys-bar-booking#5]
EPIC: Security for users

- As a **site user** I can **fill in my details with a secure log in** to **help keep my details safe**

**Acceptance Criteria**
- [ ] Create a Log in system that also needs a password to ensure user data privacy

**Tasks**
- [ ] Create an admin log in that enables it to change all settings
- [ ] Check that there are no security issues when logging in or the storing of the information in the database

**Comment by WelshDan** [comment]
Issue duplicated
